a = input('digite algo:')
print('o tipo primitivo desse valor é', type(a))
print('tem somente espeços?', a.isspace())
print('é numerico?', a.isnumeric())
print('e alfabetico?', a.isalpha())
print('e alfanumerico?', a.isalnum())
print('esta em maiúsculas?', a.isupper())
print('esta em minúscolas?', a.islower())
print('está capitalizada?', a.istitle())
